# Generated by Django 4.0.2 on 2022-03-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0002_rename_age_choices_profile_age_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile',
            new_name='profiles',
        ),
    ]
