# Generated by Django 4.0.2 on 2022-03-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0003_rename_profile_customer_profiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='age_choices',
            new_name='age_limit',
        ),
    ]
